/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminAdmissionsIndexRouteImport } from './routes/admin.admissions.index'
import { Route as AdminAdmissionsNewRouteImport } from './routes/admin.admissions.new'
import { Route as AdminAdmissionsAdmissionIdIndexRouteImport } from './routes/admin.admissions.$admissionId.index'
import { Route as AdminAdmissionsAdmissionIdEditRouteImport } from './routes/admin.admissions.$admissionId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsIndexRoute = AdminAdmissionsIndexRouteImport.update({
  id: '/admin/admissions/',
  path: '/admin/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsNewRoute = AdminAdmissionsNewRouteImport.update({
  id: '/admin/admissions/new',
  path: '/admin/admissions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsAdmissionIdIndexRoute =
  AdminAdmissionsAdmissionIdIndexRouteImport.update({
    id: '/admin/admissions/$admissionId/',
    path: '/admin/admissions/$admissionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdmissionsAdmissionIdEditRoute =
  AdminAdmissionsAdmissionIdEditRouteImport.update({
    id: '/admin/admissions/$admissionId/edit',
    path: '/admin/admissions/$admissionId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/admissions/new': typeof AdminAdmissionsNewRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
  '/admin/admissions/$admissionId/edit': typeof AdminAdmissionsAdmissionIdEditRoute
  '/admin/admissions/$admissionId/': typeof AdminAdmissionsAdmissionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/admissions/new': typeof AdminAdmissionsNewRoute
  '/admin/admissions': typeof AdminAdmissionsIndexRoute
  '/admin/admissions/$admissionId/edit': typeof AdminAdmissionsAdmissionIdEditRoute
  '/admin/admissions/$admissionId': typeof AdminAdmissionsAdmissionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/admissions/new': typeof AdminAdmissionsNewRoute
  '/admin/admissions/': typeof AdminAdmissionsIndexRoute
  '/admin/admissions/$admissionId/edit': typeof AdminAdmissionsAdmissionIdEditRoute
  '/admin/admissions/$admissionId/': typeof AdminAdmissionsAdmissionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/admissions/new'
    | '/admin/admissions/'
    | '/admin/admissions/$admissionId/edit'
    | '/admin/admissions/$admissionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/admissions/new'
    | '/admin/admissions'
    | '/admin/admissions/$admissionId/edit'
    | '/admin/admissions/$admissionId'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/admissions/new'
    | '/admin/admissions/'
    | '/admin/admissions/$admissionId/edit'
    | '/admin/admissions/$admissionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminAdmissionsNewRoute: typeof AdminAdmissionsNewRoute
  AdminAdmissionsIndexRoute: typeof AdminAdmissionsIndexRoute
  AdminAdmissionsAdmissionIdEditRoute: typeof AdminAdmissionsAdmissionIdEditRoute
  AdminAdmissionsAdmissionIdIndexRoute: typeof AdminAdmissionsAdmissionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions/': {
      id: '/admin/admissions/'
      path: '/admin/admissions'
      fullPath: '/admin/admissions/'
      preLoaderRoute: typeof AdminAdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions/new': {
      id: '/admin/admissions/new'
      path: '/admin/admissions/new'
      fullPath: '/admin/admissions/new'
      preLoaderRoute: typeof AdminAdmissionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions/$admissionId/': {
      id: '/admin/admissions/$admissionId/'
      path: '/admin/admissions/$admissionId'
      fullPath: '/admin/admissions/$admissionId/'
      preLoaderRoute: typeof AdminAdmissionsAdmissionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions/$admissionId/edit': {
      id: '/admin/admissions/$admissionId/edit'
      path: '/admin/admissions/$admissionId/edit'
      fullPath: '/admin/admissions/$admissionId/edit'
      preLoaderRoute: typeof AdminAdmissionsAdmissionIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminAdmissionsNewRoute: AdminAdmissionsNewRoute,
  AdminAdmissionsIndexRoute: AdminAdmissionsIndexRoute,
  AdminAdmissionsAdmissionIdEditRoute: AdminAdmissionsAdmissionIdEditRoute,
  AdminAdmissionsAdmissionIdIndexRoute: AdminAdmissionsAdmissionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
